### ISSUE TITLE
Allow specifying access key id and secret access key in profile configuration

### ISSUE THREAD

**Issue by MasterOdin** [dbt-athena/dbt-athena#222]
Could support for specifying the AWS access key id and secret access key values in the dbt profile? If these are not set, then the existing behavior of using automatic methods of `aws cli`/`boto3` would be used.

My use case is that I'm setting up dbt to run within a multi-tenant setup and having to specify these values via environment variables or profile name is annoying as it requires special handling vs all of the dbt Lab adapters which allows specifying the entire connection details in the profile file. Given that we're already setting the username / password of DB details in the file, I'd not consider it an additional security risk of allowing specifying the AWS credentials in this manner as well.

I'd be happy to look into providing a PR to add support for this, but want to confirm it would be accepted before starting.

**Comment by Jrmyy** [comment]
👋🏻 Hello

Thanks for the feature proposal.

I tend to agree with you that other adapters provide a way to pass the whole credentials using the profiles file. So in theory, I think it can be a feature we can add.

Now, from a practical point of view the question is about the feasibility. We use `pyathena` in order to acquire an aws connection, as you can see here. 

https://github.com/dbt-athena/dbt-athena/blob/70d26fc6d0f3adea0808aa25503def6bd912c709/dbt/adapters/athena/connections.py?plain=1#L157-L175

As far as I know, using PyAthena, I don't think you can pass `access_key` or `secret_key` directly to the `AthenaConnection` object.

I can see an alternative that would enable to configure the access key and the secret key at the adapter level is to the use the [session](https://github.com/laughingman7743/PyAthena/blob/1ee1a4dd07878d9029d0d2e2aadfadfe290aaaa6/pyathena/connection.py#L102-L103).

What do you think of that @MasterOdin ?
I don't know how you feel about this @nicor88, if you have an opinion, don't hesitate :)

**Comment by Jrmyy** [comment]
This is a good feature for a first contribution if you up to it @MasterOdin otherwise I can take care of it.

**Comment by nicor88** [comment]
@MasterOdin are you planning to develop this feature?
