### ISSUE TITLE
Seeds are deleted after upload

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#226]
I have multiple seeds in my seed folder.
Once I run `dbt seed` I can see that the csv files are uploaded to my `s3_data_dir` but one second later they are deleted.

I checked the code but could not find anything relevant for triggering the delte.
Any ideas?

Using the current main branch.

**Comment by CommonCrisis** [comment]
I tried again with the sample provided by dbt and the v 1.4.2:

dbt_project.yml:
```
seeds:
  test_models:
    +schema: seed_data
    +enabled: true
    country_codes:
      # Override column types
      +column_types:
        country_code: varchar(2)
        country_name: varchar(32)
```

and a simple csv file in `seeds/country_codes.csv`:
```
CITY,POST_CODE
Berlin,13056
Munich,87431
Hamburg,14056
```

Running `dbt seed` will execute successfully and creates the table but the uploaded csv file is empty.


Note: In 1.4.2 it is currently not possible to upload to `s3_data_dir` so it got uploaded to my `s3_staging_dir`. The big difference the file exists but is empty. Using the main branch and external location, the file gets uploaded with data and then deleted after 1 second.


Maybe someone can test on their side.

My profile:

```
      type: athena
      s3_staging_dir: s3://aws-athena-query-results-....
      s3_data_dir: s3://some-bucket/path
      s3_data_naming: schema_table
      region_name: eu-central-1
      database: awsdatacatalog
      schema: dbt
      work_group: my_work_group
      threads: 4
      num_retries: 1
      aws_profile_name: my_profile
```

**Comment by nicor88** [comment]
The new seed implementation upload the csv file to s3, creates a tmp table, then it uses a cta statement to transform the csv as parquet, then finally csv in s3 and tmp table are deleted.
Therefore deleting the csv in s3 i expected.
Is the final parquet table empty? If not it's all fine.

**Comment by CommonCrisis** [comment]
Hi,

no the final table in Athena does not contain any data.

**Comment by nicor88** [comment]
@CommonCrisis I'm able to run seed using 1.4.2, and the generated table is full with the codes, could you please provide the following:

- OS where you run your dbt models
- the generated sql for seeds - pick that from the workgroup where you run dbt, or run dbt in debug mode (`dbt -d seed`)
- a screenshoot of the s3 location where the `seed_data.countries` is located, I want to see if there are objects in there

**Comment by CommonCrisis** [comment]
Okay maybe iI am getting crazy but suddenly it just works 👯 
Idk maybe it was the fever I had on the weekend but yeah running dbt seed just does what it should do.

Sorry for the troubles caused.

**Comment by nicor88** [comment]
@CommonCrisis don't worry, maybe you saw the csv uploaded and then deleted and that created some weird feeling that something was going on. No trouble is caused :)  Thanks for checking.

**Comment by aartaria** [comment]
@nicor88 I've experienced the same behaviour as @CommonCrisis, enabling the debug mode I could spot:
```
create external table `your_schema`.`test_table_tmp` (a string, b string)
    row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
    location 's3://your-bucket/your-schema/test_table'
    tblproperties (
      'skip.header.line.count'='1'
    )
```

```
  create table "your_schema"."test_table"
  with (
    table_type='hive',
    is_external=true,external_location='s3://your-bucket/your-schema/test_table',
    format='parquet'
  )
  as
    
    select
        
              cast(nullif(a, '') as integer) as a
            , 
              cast(nullif(b, '') as integer) as b
            
    from
        "your_schema"."test_table_tmp"
```

The collision on the `external_location` looks to be the issue to me, the file gets pushed and then deleted earlier in the flow otherwise the second query could not even run, basically changing this line 

https://github.com/dbt-athena/dbt-athena/blob/70d26fc6d0f3adea0808aa25503def6bd912c709/dbt/include/athena/macros/materializations/seeds/helpers.sql#L50

to:
```
model.name + "__dbt_tmp",
```
did it for me:

That said, I do not know, why you could not reproduce the issue, it must interact with some other configs, maybe the `s3_data_naming`?

**Comment by nicor88** [comment]
@aartaria well spotted, I had a look and the issue seems indeed on based on the fact that the `model.name` is passed to https://github.com/dbt-athena/dbt-athena/blob/70d26fc6d0f3adea0808aa25503def6bd912c709/dbt/include/athena/macros/materializations/seeds/helpers.sql#L50 to adapter.upload_seed_to_s3, therefore based on the s3_data_naming in use there could be some issues.

There are some things to do:
* what you suggested IMHO must be added we pass `model.name + "__dbt_tmp"`.
* let's rename https://github.com/dbt-athena/dbt-athena/blob/70d26fc6d0f3adea0808aa25503def6bd912c709/dbt/include/athena/macros/materializations/seeds/helpers.sql#L45 to tmp_s3_location and it's relative usage.

@aartaria would you mind to open a PR (as you are the one that you spot the issue) :)
