### ISSUE TITLE
Newer versions require IAM access to athena:GetWorkGroup

### ISSUE THREAD

**Issue by brabster** [dbt-athena/dbt-athena#262]
Recent change needs athena:GetWorkGroup permission in order to check if output location enforced, with presence of workgroup in config triggering the check. See [here](https://github.com/dbt-athena/dbt-athena/blob/e818c41dcbe46dbbb251d57e418f8575c32f9707/dbt/adapters/athena/impl.py#L156)

If this permission is not granted, an AccessDeniedException is produced.

This means that eg. seeding a table fails due to [this call in macro](https://github.com/dbt-athena/dbt-athena/blob/e818c41dcbe46dbbb251d57e418f8575c32f9707/dbt/include/athena/macros/materializations/models/table/create_table_as.sql#L17)

Earlier versions didn't need this permission, and it seems safe to catch access denied and proceed if the permission is not granted, allowing the operation to fail if the output location is enforced?

**Comment by nicor88** [comment]
I'm not in favor of catching such permission error. 
IMHO is better to maybe document a bit more the minum permissions needed to work with this adapter. 
Also, `athena:GetWorkGroup` is just a read permission.

**Comment by nicor88** [comment]
@brabster you raised a really good point, there was a breaking change also for other reasons, we didn't foresee that unfortunately, otherwise, we will have highlighted it in the release notes.

Regarding seeds as iceberg: nice feature request, they are not supported currently. 
As it is now you can just seed the table as parquet, then maybe consider to use the seeded table to create a model as iceberg.

Could you give me your use case about using iceberg with seeds? (note we could consider to implement that in the future).

**Comment by brabster** [comment]
Not an issue about the breaking change, these things happen! There seem be a few differences actually in behaviour from 1.3.5 so I forked from that tag instead of main to get us working for now. I'm not about until next week now but I'll check back in when I get back to it.

**Comment by nicor88** [comment]
@brabster ok, consider then raising the specific errors relative to seeds in this one, or consider proposing a fix .

Regarding iceberg for seeds, will be good to open another issue and the reason why would be needed.

**Comment by nicor88** [comment]
Yes we should close we have this: https://github.com/dbt-athena/dbt-athena/issues/291 and this https://github.com/dbt-athena/dbt-athena/issues/302 to tackle this issue.
