### ISSUE TITLE
Automatically add lakeformation tags in case we let dbt create databases

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#373]
Generally I have the creation of databases outside dbt (terraform or cdk)- including lakeformation tagging.

There are some scenarios like running dbt in the CI, where I would like to run in a freshly created db - (that already works) and automatically tag that db with some default tags.

Looking [here](https://github.com/dbt-athena/dbt-athena/blob/b8e3e8fbdc8adf898fd67a153c4b18ca605b1f51/dbt/include/athena/macros/adapters/schema.sql#L1C1-L5C15) seems like that we just miss a call to default tags - that can be parsed from dbt_project.yml or from profile config e.g. default_lakeformation_tags

**Comment by svdimchenko** [comment]
@nicor88 this feature was implemented at first time of lakeformation was integrated. However in this case we may have the following problem: what if you need to modify LF-tags ? How would you do that ? If you manage LF tags somehow outside dbt (I use terraform, for instance) then you'll need to import database into terraform state.
If you need to create some temp databases on CI/CD stage, then you can create database without LF tags as it's done now.

Otherwise we can implement LF-tags management for databases as well, but in this case full CRUD must be implemented. And we should sort out when should we run that LF-tags update operation.

**Comment by nicor88** [comment]
This specific issue imply cases where db needs to be created in dbt for example for ephemeral setups - like CI.
I wont make it super complicated to cover corner cases, and still recommend final users to have such process for long lived production databases outside dbt

**Comment by svdimchenko** [comment]
I got your point. But why do you need LF lags for such databases at all? I'm creating such temp dbs with ci without tags and it works ok, coz all users and services have access to tagged resources only.

**Comment by nicor88** [comment]
@svdimchenko table creations and all dbt run commands should work. I will give it a try in the next days without ci to see if all works, in case I will just close this one. Thank you for the clarification.

**Comment by svdimchenko** [comment]
If we talk about implementation, it can be easily added of course on macro you have mentioned. But I'm just not sure if we do need to add this feature to the adapter. Just ping me if you'll need support with that.
