### ISSUE TITLE
Run pre-hook:  MSCK REPAIR TABLE but got error.

### ISSUE THREAD

**Issue by binhnq94** [dbt-athena/dbt-athena#468]
I set pre-hook: MSCK REPAIR TABLE, but got error as bellow:
`[ErrorCategory:USER_ERROR, ErrorCode:DDL_FAILED], Detail:FAILED: ParseException line 1:216 cannot recognize input near '<EOF>' '<EOF>' '<EOF>'`

**Comment by nicor88** [comment]
@binhnq94 could be related to this https://github.com/dbt-athena/dbt-athena/issues/182

If you use MSCK repair for a table source or ref you might want to use `render_hive()` on the relation.

**Comment by binhnq94** [comment]
@nicor88 I use plan text instead of macro as bellow:
```
 MSCK REPAIR TABLE `awsdatacatalog`.`raw`.`my_table_name`
```
I try it on Athena UI got no error.

**Comment by nicor88** [comment]
I believe that those ` might be replace in the query execution, and the might have be rededered wrongly.

I recommend that you do the following:
* put your raw table inside sources https://docs.getdbt.com/reference/source-configs
* when you have your raw data table in sources you must use that as pre-hook `"MSCK REPAIR TABLE {{ source('raw', 'my_table_name').render_hive() }}"`

the issue is what is described here https://github.com/dbt-athena/dbt-athena/issues/182 and anyhow if your raw table is created somehow outside dbt is a good practise to add it to sources to have a full project lineage.

**Comment by binhnq94** [comment]
I config as you say:
```
{{
    config(
        pre_hook="MSCK REPAIR TABLE {{ source('raw', 'my_table_name').render_hive() }}"
    )
}}
```
But still got: ` FAILED: ParseException line 1:216 cannot recognize input near '<EOF>' '<EOF>' '<EOF>'`

**Comment by binhnq94** [comment]
I checked the query on the Recent queries of Athena UI. I found the bug is `MSCK REPAIR TABLE` in the same line with `-- /* {"app": "dbt", "dbt_version": "1.6.6", "profile_name": "my_profile", ...}` => No query to run.
We need a break to split the query into 2 lines.

**Comment by binhnq94** [comment]
It is clear that athena adapter add `\n` between `query_comment` and `sql`: 
https://github.com/dbt-athena/dbt-athena/blob/main/dbt/adapters/athena/query_headers.py#L33

**Comment by binhnq94** [comment]
I think there is a implicit logic in Athena.
To fix it, I add a `--to-fix\n` before `MSCK ...` as bellow 
```
{{
config(
    pre_hook="--to-fix\nMSCK REPAIR TABLE {{ source('raw', 'my_table_name').render_hive() }}"
)
}}
```

**Comment by nicor88** [comment]
Thanks for spotting this @binhnq94 , I believe that in the issue in this case is due to the fact that the adapter add a query comment, and that leads to not having a new line.

We can do something similar to what is done to alter statements, see this: https://github.com/dbt-athena/dbt-athena/blob/116fd7312d0a434d067df99d287044c9acf06100/dbt/adapters/athena/query_headers.py#L19

we can simply add `msck` in the list of statements to exclude. It should work. If you want to you even submit a PR:)

**Comment by binhnq94** [comment]
@nicor88 Let me try.

**Comment by binhnq94** [comment]
@nicor88 I created PR #469.

**Comment by nicor88** [comment]
@binhnq94 did you try if it works for you?

**Comment by binhnq94** [comment]
@nicor88 I work well on my project.
When will we have new version ? =))

**Comment by nicor88** [comment]
@binhnq94 we are still planning when to release it, might be soon, as we have quite some bug fixed that must be released.

Thanks for your contribution and spotting the issue.
