### ISSUE TITLE
Permanently failing models take 80 seconds+ to come back

### ISSUE THREAD

**Issue by dacreify** [dbt-athena/dbt-athena#473]
Often I'll have an SQL or permissions error that causes a permanent failure of a model. If I run the compiled query in the Athena console it comes back immediately with the error. However running the model in `dbt-athena` takes upwards of 80 seconds before the model fails and the error is returned.

It seems like a retry of a permanent failure is happening at some layer. Not sure if it's a layer `dbt-athena` controls but if so it'd be nice to fail faster.

**Comment by nicor88** [comment]
@dacreify it's really hard to debug and help you out with this issue, we need a bit more context.
How does your model config look like?

**Comment by dacreify** [comment]
@nicor88 Thanks for your reply. Retrying makes sense for transient issues, but for permanent ones they just slow down development. It may be difficult to differentiate between the two classes depending on how clear about it the responses from Athena are.

In terms of reproducing just throwing e.g. `select blert` into a model and running it will show the ~ 80 second wait.

**Comment by nicor88** [comment]
@dacreify if retying is the root cause of this issue (I believe it is, default num_retries is 5, and there is also some default backoff, that means that for some retries the waited interval is longer) , maybe is worth to follow this:

* in your **development** environment you should use a fail fast approach, therefore use `num_retries: 0` (I generally use that)
* in **staging/production** environments consider to use num_retries > 0, this is really depends on the type of orchestration that you use. e.g. in Airflow or step functions you can setup more advanced retries.

**Comment by nicor88** [comment]
@dacreify any input here? IMHO there is no much that we can do, except than providing guidelines on how retries can be configured to avoid this beavior.

**Comment by dacreify** [comment]
@nicor88 Apologies for the slow reply. Yes using `num_retries` sounds like a nice, straight-forward solution!

**Comment by nicor88** [comment]
@dacreify please refer to this https://github.com/dbt-athena/dbt-athena/issues/473#issuecomment-1778558998, again the root cause is that if num_retries is not explicitly configure, it will fallback to 5...and backhoff kicks in. So you wait an eternity before having an "fast" feedback cycle.
