### ISSUE TITLE
Support on schema change for iceberg incremental

### ISSUE THREAD

**Issue by nicor88** [dbt-athena/dbt-athena#51]
# What
Add support on_schema_change for iceberg incremental.
Append mode seems supported, we need just to cover the `merge` incremental behavior.

**Comment by Jrmyy** [comment]
I tested without modifying the current implementation of `on_schema_change`,  just adding it to the merge method. But it cannot be done that way because : the check of the data types to check if data types changes exist are made between the tmp_table (a parquet table) and the existing relation (an iceberg relation).

Therefore :
- Since merge is only available with v3 engine, one solution could be to first implement ctas for Iceberg and then use the ctas, and only the ctas, to create the temp table for incremental (i.e. temp table will be in iceberg in one query), and we can then use the current implementation of `on_schema_change`.
- Create a temp table in Iceberg format when doing incremental. This process seems super heavy to me and can lead to a lot of errors / edge cases. In details, for incremental merge in iceberg, it will lead to  :
  - create a temp table in iceberg
    - create a temp table in parquet for the incremental temp table in iceberg
    - create the incremental temp table in iceberg
    - insert from temp table in paruqet in the incremental temp table in iceberg
  - check the on schema change
  - merge
