### ISSUE TITLE
[Feature] Rename unique_key to unique_columns or merge_on_columns

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#621]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

Maybe this is not needed but for me it was not clear that in a iceberg merge model `unique_key` takes a list of values.
The issue I had is that the target table got more or less a full scan if I only provide my `unique_key` column (200 GB per run). Now that I added a list of columns: my unique key AND my partition columns the scan of my target table went down to like 30 GB per run. So each run went from 1 $ to only 0.15 $.

The `incremental_predicates` did not really help reducing the scan limit, cause I cannot hard code a date range in my model due to inital runs (splitting the src data into chunks with the `__PERIOD_FILTER__` macro.

Or we need to update the documentation a little. Do explain that the `unique_column` is just doing a matching on clause based on the provided column(s).

Hope it is clear, what my issue/concern is.

### Describe alternatives you've considered

Rename the `unique_key` paramter to e.g. `merge_on_columns`. Maybe someone has a better name for that.

### Who will this benefit?

Everyone using incremental iceberg models

### Are you interested in contributing this feature?

Sure

**Comment by Jrmyy** [comment]
👋🏻 Hello

Thanks for raising this issue. I am not sure we should go down this renaming because `unique_key` is what is available in dbt documentation when it comes to merge incremental models (https://docs.getdbt.com/docs/build/incremental-models).

If we look at dbt-athena documentation (https://dbt-athena.github.io/docs/configuration/materializations/iceberg#incremental-tables) it is stated:

 >unique_key (required): columns that define a unique record in the source and target tables.

We can change columns to something more meaningful like `column or list of columns` but I am not in favour of renaming `unique_key`.

What do you think @nicor88 @svdimchenko ?

**Comment by nicor88** [comment]
Absolutely agree with @Jrmyy, we should use a canonical name used across adapters.
And yes, we could improve docs to make it more clear, even providing an example on the query that is generated.

**Comment by CommonCrisis** [comment]
Okay, then I will take care of the docs I guess :)
